from pydantic import BaseModel, Field
from typing import List, Dict, Optional
from datetime import datetime  

class FundSchema(BaseModel):
    scheme_code: int
    isin_div_payout_growth: str
    isin_div_reinvestment: str | None = None
    scheme_name: str
    net_asset_value: float
    date: datetime  
    scheme_type: str
    scheme_category: str
    mutual_fund_family: str
    sip: Optional[int] = None  # Optional for input, generated by backend
    invested_value:Optional[float] = None
    created_at: Optional[datetime] = None  # Optional for input, generated by backend
    updated_at: Optional[datetime] = None
   

class PortfolioSchema(BaseModel):
    user_id: str
    funds: List[FundSchema] = Field(default_factory=list)

class FundFamilyRequest(BaseModel):
    fund_family: str
